'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Player={id:string;first_name:string;last_name:string;phone:string;player_code:string;team:string;flag:string;points:number;wins:number;losses:number;goals_for:number;goals_against:number};
type Match={id:string;round:string;kickoff:string;team_a:string;flag_a:string;team_b:string;flag_b:string;score_a:number;score_b:number;winner:string|null;status:string;minute?:number;extra_time?:number;highlights_url?:string};
type Pick={id:string;participant_id:string;match_id:string;selected_team:string};

const ADMIN_PHONE='7209880163';
const ADMIN_PASSCODE='3737';
const YEAR=2026;
const teams=[['Argentina','🇦🇷'],['Brazil','🇧🇷'],['France','🇫🇷'],['England','🏴'],['Spain','🇪🇸'],['Germany','🇩🇪'],['Portugal','🇵🇹'],['USA','🇺🇸'],['Mexico','🇲🇽'],['Netherlands','🇳🇱'],['Japan','🇯🇵'],['Canada','🇨🇦'],['Morocco','🇲🇦'],['Belgium','🇧🇪'],['Colombia','🇨🇴'],['Paraguay','🇵🇾'],['Norway','🇳🇴'],['Sweden','🇸🇪'],['Ecuador','🇪🇨'],['Senegal','🇸🇳']];

function clean(v:string){return v.replace(/\D/g,'')}
function smsPhone(v:string){const d=clean(v);return d.length===10?`+1${d}`:d.startsWith('1')?`+${d}`:v}
async function sendSMS(phones:string[],message:string){if(!phones.length)return;await fetch('/api/sms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phones:[...new Set(phones)].map(smsPhone),message})}).catch(()=>{})}
function teamPower(team:string){const p:Record<string,number>={Brazil:92,France:90,Spain:88,Germany:86,Argentina:86,England:84,Portugal:83,Netherlands:82,Belgium:80,Canada:74,Japan:76,Morocco:77,USA:76,Mexico:75,Colombia:78,Switzerland:76,Croatia:78,Senegal:75,Sweden:74,Norway:73,Paraguay:72,Ecuador:72,Egypt:74,'DR Congo':70};return p[team]??65}
function teamChance(a:string,b:string){const pa=teamPower(a),pb=teamPower(b),ca=Math.round((pa/(pa+pb))*100);return[ca,100-ca]}
function pct(n:number,d:number){return d?Math.round((n/d)*100):0}
function isLive(m:Match){return(m.status||'').toLowerCase()==='live'}
function isSched(m:Match){return(m.status||'').toLowerCase()==='scheduled'}
function isFinal(m:Match){return(m.status||'').toLowerCase()==='final'}
function kickoffValue(k:string){const s=(k||'').replace(/\s+/g,' ').replace(/(\d)(AM|PM)/i,'$1 $2').trim();const t=Date.parse(`${s} ${YEAR}`);return Number.isNaN(t)?Number.MAX_SAFE_INTEGER:t}
function byKickoff(a:Match,b:Match){return kickoffValue(a.kickoff)-kickoffValue(b.kickoff)||String(a.id).localeCompare(String(b.id))}
function pickIcon(m:Match,p?:Pick){if(!p)return'▫️';if(!isFinal(m)||!m.winner)return'🎟️';return p.selected_team===m.winner?'🏆😀':'😞⚽'}
function pickLabel(m:Match,p?:Pick){if(!p)return'No pick';if(!isFinal(m)||!m.winner)return`Pick: ${p.selected_team}`;return p.selected_team===m.winner?`Winner pick: ${p.selected_team}`:`Missed pick: ${p.selected_team}`}
function playerChance(p:Player,players:Player[]){if(!players.length)return 0;const max=Math.max(...players.map(x=>x.points||0),0),base=(p.points||0)+1,total=players.reduce((s,x)=>s+(x.points||0)+1,0),bonus=(p.points||0)===max?8:0;return Math.min(99,Math.max(1,Math.round((base/total)*100+bonus)))}
function needText(player:Player,matches:Match[],picks:Pick[]){const m=matches.find(x=>!isFinal(x));if(!m)return'All listed games are final. Watch for admin updates.';const p=picks.find(x=>x.participant_id===player.id&&x.match_id===m.id);return p?`Next need: ${p.selected_team} over ${p.selected_team===m.team_a?m.team_b:m.team_a}`:`Needs a pick for ${m.team_a} vs ${m.team_b}`}
function roadToVictory(player:Player,players:Player[],matches:Match[],picks:Pick[]){const pp=picks.filter(p=>p.participant_id===player.id),remaining=matches.filter(m=>!isFinal(m));const needs=remaining.slice(0,5).map(m=>{const p=pp.find(x=>x.match_id===m.id);return p?`${p.selected_team} over ${p.selected_team===m.team_a?m.team_b:m.team_a}`:`Pick ${m.team_a} vs ${m.team_b}`});const rival=[...players].filter(p=>p.id!==player.id).sort((a,b)=>(b.points||0)-(a.points||0))[0];return{needs,rival,jump:Math.min(99,playerChance(player,players)+20)}}
function featured(matches:Match[]){const live=matches.filter(isLive);if(live.length)return{label:'LLSN LIVE NOW',matches:live};const next=matches.find(isSched);return{label:'LLSN NEXT UP',matches:next?[next]:[]}}

export default function Home(){
 const[players,setPlayers]=useState<Player[]>([]),[matches,setMatches]=useState<Match[]>([]),[picks,setPicks]=useState<Pick[]>([]),[status,setStatus]=useState(''),[flash,setFlash]=useState(''),[soundEnabled,setSoundEnabled]=useState(false),[admin,setAdmin]=useState({phone:'',passcode:''}),[isAdmin,setIsAdmin]=useState(false),[broadcast,setBroadcast]=useState(''),[chat,setChat]=useState<any[]>([]),[chatText,setChatText]=useState(''),[selectedPlayer,setSelectedPlayer]=useState<Player|null>(null),[form,setForm]=useState({first_name:'',last_name:'',phone:'',player_code:'',team:'Argentina',flag:'🇦🇷'});
 const audioRef=useRef<AudioContext|null>(null);
 useEffect(()=>{load();const ch=supabase.channel('llsn-live-v15-final').on('postgres_changes',{event:'*',schema:'public',table:'participants'},liveUpdate).on('postgres_changes',{event:'*',schema:'public',table:'wc_matches'},liveUpdate).on('postgres_changes',{event:'*',schema:'public',table:'match_picks'},liveUpdate).on('postgres_changes',{event:'*',schema:'public',table:'fan_messages'},liveUpdate).subscribe();const timer=setInterval(load,2500),onFocus=()=>load(),onVisible=()=>{if(!document.hidden)load()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisible);supabase.removeChannel(ch)}},[]);
 function beep(){if(!soundEnabled)return;try{const w=window as any,ctx:AudioContext=audioRef.current??new(w.AudioContext||w.webkitAudioContext)();audioRef.current=ctx;const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;o.connect(g);g.connect(ctx.destination);g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.2,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);o.start();o.stop(ctx.currentTime+.3)}catch{}}
 async function liveUpdate(){beep();setFlash('⚡ LIVE UPDATE — LLSN board refreshed');setTimeout(()=>setFlash(''),2200);await load()}
 async function load(){const{data:p,error:pe}=await supabase.from('participants').select('*').order('created_at');const{data:m,error:me}=await supabase.from('wc_matches').select('*');const{data:k,error:ke}=await supabase.from('match_picks').select('*');if(pe||me||ke){setStatus(pe?.message||me?.message||ke?.message||'Database error');return}setPlayers((p||[])as Player[]);setMatches(((m||[])as Match[]).sort(byKickoff));setPicks((k||[])as Pick[]);const{data:c}=await supabase.from('fan_messages').select('*').order('created_at',{ascending:false}).limit(30);setChat((c||[]).reverse())}
 const me=players.find(p=>clean(p.phone)===clean(form.phone)&&p.player_code===form.player_code);
 async function savePlayer(){if(!form.first_name||!form.last_name||clean(form.phone).length<10||form.player_code.length!==4){setStatus('Enter name, mobile number, and 4-digit code.');return}const phone=clean(form.phone),existing=players.find(p=>clean(p.phone)===phone&&p.player_code===form.player_code);if(existing){const{error}=await supabase.from('participants').update({first_name:form.first_name,last_name:form.last_name,team:form.team,flag:form.flag}).eq('id',existing.id);if(error){setStatus(error.message);return}setStatus('Player updated. Make picks below.')}else{const{error}=await supabase.from('participants').insert({first_name:form.first_name,last_name:form.last_name,phone,player_code:form.player_code,team:form.team,flag:form.flag,points:0,wins:0,losses:0,goals_for:0,goals_against:0});if(error){setStatus(error.message);return}await sendSMS(players.map(p=>p.phone),`${form.first_name} joined Lytle Lemon FIFA World Cup Live as ${form.flag} ${form.team}!`);setStatus('Player saved. Make picks below.')}await load()}
 async function savePick(m:Match,team:string){const player=players.find(p=>clean(p.phone)===clean(form.phone)&&p.player_code===form.player_code);if(!player){setStatus('Save player first, or enter the same phone + 4-digit code.');return}const{error}=await supabase.from('match_picks').upsert({participant_id:player.id,match_id:m.id,selected_team:team,updated_at:new Date().toISOString()},{onConflict:'participant_id,match_id'});if(error){setStatus(error.message);return}setStatus(`Pick saved: ${team}`);await load()}
 async function sendChat(){if(!chatText.trim())return;const playerName=me?`${me.first_name} ${me.last_name}`:'Fan';const{error}=await supabase.from('fan_messages').insert({player_name:playerName,message:chatText.trim()});if(error){setStatus(error.message);return}setChatText('');await load()}
 async function recalc(){const finals=matches.filter(m=>isFinal(m)&&m.winner);for(const p of players){let points=0,wins=0,losses=0;for(const m of finals){const pick=picks.find(x=>x.participant_id===p.id&&x.match_id===m.id);if(!pick)continue;if(pick.selected_team===m.winner){points+=3;wins++}else losses++}await supabase.from('participants').update({points,wins,losses}).eq('id',p.id)}await load()}
 async function updateMatch(m:Match,a:number,b:number,st:string,minute=0,highlights_url='',extra_time=0){const winner=st==='final'&&a!==b?(a>b?m.team_a:m.team_b):null;const{error}=await supabase.from('wc_matches').update({score_a:a,score_b:b,status:st,winner,minute,extra_time,highlights_url,updated_at:new Date().toISOString()}).eq('id',m.id);if(error){setStatus(error.message);return}await sendSMS(players.map(p=>p.phone),`LLSN LIVE UPDATE: ${m.flag_a} ${m.team_a} ${a}-${b} ${m.flag_b} ${m.team_b}${winner?`. Winner: ${winner}`:''}`);await recalc();setStatus('Match updated. Leaderboard recalculated.')}
 async function broadcastSMS(){if(!broadcast.trim())return;await sendSMS(players.map(p=>p.phone),`LLSN BROADCAST: ${broadcast}`);setBroadcast('');setStatus('Broadcast sent if Twilio is configured.')}
 function login(){const ok=clean(admin.phone)===ADMIN_PHONE&&admin.passcode===ADMIN_PASSCODE;setIsAdmin(ok);setStatus(ok?'Admin open.':'Admin login failed.')}
 const sorted=useMemo(()=>[...matches].sort(byKickoff),[matches]),board=useMemo(()=>[...players].sort((a,b)=>(b.points||0)-(a.points||0)||(b.wins||0)-(a.wins||0)),[players]),live=sorted.filter(isLive),upcoming=sorted.filter(isSched),finals=sorted.filter(isFinal),feat=useMemo(()=>featured(sorted),[sorted]),upset=sorted.find(m=>isFinal(m)&&m.winner&&teamChance(m.team_a,m.team_b)[m.winner===m.team_a?0:1]<45);
 const ticker=[live.length?`🔴 LIVE: ${live[0].team_a} ${live[0].score_a??0}-${live[0].score_b??0} ${live[0].team_b}`:null,board[0]?`🏆 Leader: ${board[0].flag} ${board[0].first_name} with ${board[0].points||0} pts`:null,upcoming[0]?`⏭ Next: ${upcoming[0].team_a} vs ${upcoming[0].team_b} • ${upcoming[0].kickoff}`:null,upset?`🚨 Upset Alert: ${upset.winner} shocked the board`:null,'📺 Welcome to Lytle Lemon Sports Network'].filter(Boolean);
 return <main className="wrap">
  <section className="hero"><div><h1>🏆 Lytle Lemon Sports Network</h1><p className="muted">Vegas-style live board, sorted upcoming matches, pick results, admin scoring, SMS broadcasts, and leaderboard updates.</p></div><div className="heroActions"><button className="ghost" onClick={()=>{setSoundEnabled(true);setStatus('Sound enabled.');beep()}}>🔊 Enable Sound</button><div className="badge">V1.5 FINAL</div></div></section>
  <section className="liveFlash">{ticker.join('     •     ')}</section>{flash&&<section className="liveFlash">{flash}</section>}
  <section className="espnNow"><div className="espnNowHeader"><span>{feat.label}</span><span>LYTLE LEMON SPORTSBOOK</span></div>{feat.matches.length?feat.matches.map(m=><div className="espnNowGame" key={m.id}><div className="espnNowStatus">{isLive(m)?<b className="livePulse">● LIVE</b>:<b>NEXT MATCH</b>}{isLive(m)&&<span>{m.minute||0}'{m.extra_time?` +${m.extra_time}`:''}</span>}</div><div className="espnNowTeams"><div>{m.flag_a} <b>{m.team_a}</b></div><strong>{m.score_a??0}</strong><span>vs</span><strong>{m.score_b??0}</strong><div>{m.flag_b} <b>{m.team_b}</b></div></div><div className="espnNowMeta">{m.round} • {m.kickoff}</div></div>):<div className="espnNowEmpty">No live or upcoming matches yet.</div>}</section>
  <div className="grid"><section className="card pickBoard stadium"><h2>🔥 LIVE CENTER</h2>{live.length?live.map(m=><ScoreCard key={m.id} m={m} picks={picks}/>):<p className="muted">No match marked live yet. Admin can set one live below.</p>}{upset&&<div className="locked">🚨 Upset alert: {upset.winner} beat the odds!</div>}</section><section className="card"><h2>⏭ Upcoming Matches <span className="muted">(in order)</span></h2><div className="list">{upcoming.length?upcoming.map(m=><UpcomingMatch key={m.id} m={m}/>):<p className="muted">No upcoming matches.</p>}</div></section><section className="card fanZone"><h2>💬 Fan Zone</h2><div className="chatBox">{chat.map(m=><div className="chatMsg" key={m.id}><b>{m.player_name}</b><span>{m.message}</span></div>)}</div><div className="row"><input placeholder="Talk some friendly trash..." value={chatText} onChange={e=>setChatText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')sendChat()}}/><button onClick={sendChat}>Send</button></div></section><section className="card"><h2>🏆 Live Leaderboard</h2><div className="list">{board.map((p,i)=><div className="item" key={p.id} onClick={()=>setSelectedPlayer(p)} style={{cursor:'pointer'}}><span>{i===0?'🥇':i===1?'🥈':i===2?'🥉':`#${i+1}`} {p.flag} {p.first_name} {p.last_name}<br/><span className="muted">{p.team} • W {p.wins||0} L {p.losses||0} • Chance to win: {playerChance(p,players)}% • Tap to view picks</span><div className="meter"><i style={{width:`${playerChance(p,players)}%`}}></i></div></span><b>{p.points||0} pts</b></div>)}</div></section><section className="card"><h2>Join / Update Player</h2><div className="row"><input placeholder="First name" value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/><input placeholder="Last name" value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></div><br/><div className="row"><input placeholder="U.S. mobile number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="4-digit code" maxLength={4} value={form.player_code} onChange={e=>setForm({...form,player_code:e.target.value.replace(/\D/g,'')})}/></div><p className="hint">Same phone + code lets a player update picks anytime.</p><label className="muted">Tournament team</label><select value={form.team} onChange={e=>{const t=teams.find(x=>x[0]===e.target.value)!;setForm({...form,team:t[0],flag:t[1]})}}>{teams.map(t=><option key={`${t[0]}-${t[1]}`} value={t[0]}>{t[1]} {t[0]}</option>)}</select><br/><br/><button onClick={savePlayer}>Save Player</button><p className="muted">{status}</p><div className="invite"><b>Share Link</b><span>{typeof window==='undefined'?'':window.location.origin}</span></div></section></div>
  <section className="card"><h2>⚽ Make / Change Picks</h2><button onClick={()=>setStatus('Picks submitted / updated.')}>Submit / Update Picks</button><br/><br/>{!me&&<p className="locked">Save player first. Then pick every match here.</p>}<div className="bracket">{sorted.map(m=>{const pick=me?picks.find(x=>x.participant_id===me.id&&x.match_id===m.id):undefined;return <div className="match" key={m.id}><div className="row"><b>{m.round}</b><span className="badge">{isLive(m)?'🔴 LIVE':m.status}</span></div><p className="muted">{m.kickoff}</p><div className="team"><span>{m.flag_a} {m.team_a}</span><b>{m.score_a??0}</b></div><div className="team"><span>{m.flag_b} {m.team_b}</span><b>{m.score_b??0}</b></div><p className="winnerText">{pickIcon(m,pick)} {pickLabel(m,pick)}</p>{m.winner&&<p className="winnerText">Winner: {m.winner}</p>}<div className="choiceRow"><button className={pick?.selected_team===m.team_a?'selectedChoice':'ghost'} onClick={()=>savePick(m,m.team_a)}>Submit / Update: {m.flag_a} {m.team_a}</button><button className={pick?.selected_team===m.team_b?'selectedChoice':'ghost'} onClick={()=>savePick(m,m.team_b)}>Submit / Update: {m.flag_b} {m.team_b}</button></div></div>})}</div></section>
  <section className="card bracketCard tvBoard"><h2>📺 LLSN Match Board</h2><h3>🔴 Live</h3>{live.length?live.map(m=><ScoreCard key={`l-${m.id}`} m={m} picks={picks}/>):<p className="muted">No live matches right now.</p>}<h3>⏭ Upcoming</h3>{upcoming.map(m=><ScoreCard key={`u-${m.id}`} m={m} picks={picks}/>)}<h3>✅ Finals</h3>{finals.map(m=><ScoreCard key={`f-${m.id}`} m={m} picks={picks}/>)}</section>
  {!isAdmin?<section className="card"><h2>Admin</h2><div className="row"><input placeholder="Admin mobile" value={admin.phone} onChange={e=>setAdmin({...admin,phone:e.target.value})}/><input placeholder="Passcode" type="password" value={admin.passcode} onChange={e=>setAdmin({...admin,passcode:e.target.value})}/><button onClick={login}>Open Admin</button></div></section>:<section className="card admin"><h2>Admin Control Center</h2><h3>Broadcast SMS</h3><div className="row"><input placeholder="Message everyone" value={broadcast} onChange={e=>setBroadcast(e.target.value)}/><button onClick={broadcastSMS}>Send SMS</button></div><h3>Live Match Updates</h3><div className="list">{sorted.map(m=><AdminMatch key={m.id} m={m} save={updateMatch}/>)}</div></section>}
  {selectedPlayer&&<div className="modalBackdrop" onClick={()=>setSelectedPlayer(null)}><div className="modalCard" onClick={e=>e.stopPropagation()}><button className="ghost" onClick={()=>setSelectedPlayer(null)}>Close</button><h2>{selectedPlayer.flag} {selectedPlayer.first_name} {selectedPlayer.last_name}'s Picks</h2><p className="muted">{selectedPlayer.team} • {selectedPlayer.points||0} pts • Chance to win: {playerChance(selectedPlayer,players)}%</p><div className="locked">🎯 {needText(selectedPlayer,sorted,picks)}</div>{(()=>{const r=roadToVictory(selectedPlayer,players,sorted,picks);return <div className="roadCard"><h3>🏆 Road to Victory</h3><p><b>If these happen...</b></p><ul>{r.needs.map((n,i)=><li key={i}>✅ {n}</li>)}</ul><p><b>Chance jumps to:</b> {r.jump}%</p><p><b>Most dangerous opponent:</b> {r.rival?`${r.rival.flag} ${r.rival.first_name}`:'Nobody yet'}</p></div>})()}<div className="list">{sorted.map(m=>{const pick=picks.find(x=>x.participant_id===selectedPlayer.id&&x.match_id===m.id);return <div className="item" key={m.id}><span><b>{m.flag_a} {m.team_a} {m.score_a??0} - {m.score_b??0} {m.flag_b} {m.team_b}</b><br/><span className="muted">{m.round} • {m.kickoff} • {m.status}</span><br/>{pickIcon(m,pick)} {pickLabel(m,pick)}</span><b>{m.winner?`Winner: ${m.winner}`:'TBD'}</b></div>})}</div></div></div>}
  <div className="footer"><strong>🏆 Lytle Lemon Sports Network</strong><br/><span>Version 1.5 — Final Live-App Polish</span><br/><span>Created by Lytle Lemon</span><br/><span>Powered by Lytle Lemon Technologies</span><br/><span>Build Date: July 4, 2026</span><br/><span>© 2026 Lytle Lemon Technologies. All Rights Reserved.</span></div>
 </main>
}

function UpcomingMatch({m}:{m:Match}){return <div className="item"><span><b>{m.flag_a} {m.team_a} <span className="muted">vs</span> {m.team_b} {m.flag_b}</b><br/><span className="muted">{m.round} • {m.kickoff}</span></span><b>🏆😀</b></div>}
function ScoreCard({m,picks}:{m:Match;picks:Pick[]}){const[a,b]=teamChance(m.team_a,m.team_b),total=picks.filter(p=>p.match_id===m.id).length,pa=pct(picks.filter(p=>p.match_id===m.id&&p.selected_team===m.team_a).length,total),pb=pct(picks.filter(p=>p.match_id===m.id&&p.selected_team===m.team_b).length,total),live=isLive(m);return <div className="match"><div className="row"><b>{m.round}</b><span className="badge">{live?'🔴 LIVE':m.status}</span></div><p className="muted">{m.kickoff}</p><div className="team"><span>{m.flag_a} {m.team_a}</span><b>{m.score_a??0}</b></div><div className="meter"><i style={{width:`${a}%`}}></i></div><p className="muted">Win chance: {m.team_a} {a}% • Lytle Lemon picks {pa}%</p><div className="team"><span>{m.flag_b} {m.team_b}</span><b>{m.score_b??0}</b></div><div className="meter"><i style={{width:`${b}%`}}></i></div><p className="muted">Win chance: {m.team_b} {b}% • Lytle Lemon picks {pb}%</p>{live&&<p className="winnerText">⏱ {m.minute||0}' {m.extra_time?<span className="extraTime">+{m.extra_time}</span>:null}</p>}{m.highlights_url&&<p><a className="highlightLink" href={m.highlights_url} target="_blank">🎥 Watch Highlights</a></p>}{m.winner&&<p className="winnerText">Winner: {m.winner}</p>}</div>}
function AdminMatch({m,save}:{m:Match;save:(m:Match,a:number,b:number,s:string,minute:number,highlights_url:string,extra_time?:number)=>void}){const[a,setA]=useState(m.score_a||0),[b,setB]=useState(m.score_b||0),[s,setS]=useState(m.status||'scheduled'),[min,setMin]=useState(m.minute||0),[extra,setExtra]=useState(m.extra_time||0),[hl,setHl]=useState(m.highlights_url||'');useEffect(()=>{setA(m.score_a||0);setB(m.score_b||0);setS(m.status||'scheduled');setMin(m.minute||0);setExtra(m.extra_time||0);setHl(m.highlights_url||'')},[m]);return <div className="item adminItem"><span>{m.flag_a} {m.team_a} vs {m.flag_b} {m.team_b}<br/><span className="muted">{m.kickoff}</span></span><div className="statGrid"><input type="number" value={a} onChange={e=>setA(Number(e.target.value))}/><input type="number" value={b} onChange={e=>setB(Number(e.target.value))}/><input type="number" placeholder="Minute" value={min} onChange={e=>setMin(Number(e.target.value))}/><input type="number" placeholder="Extra" value={extra} onChange={e=>setExtra(Number(e.target.value))}/><select value={s} onChange={e=>setS(e.target.value)}><option value="scheduled">Scheduled</option><option value="live">Live</option><option value="final">Final</option></select><input placeholder="Highlights URL" value={hl} onChange={e=>setHl(e.target.value)}/><button onClick={()=>save(m,a,b,s,min,hl,extra)}>Update</button></div></div>}
